/**
 *
 * $Id$
 */
package inf5153emf.validation;

import inf5153emf.Memento;
import inf5153emf.Message;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link inf5153emf.Historique}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HistoriqueValidator {
	boolean validate();

	boolean validateMemento(EList<Memento> value);
	boolean validateMessage(Message value);
	boolean validateState(String value);
}
