/**
 *
 * $Id$
 */
package inf5153emf.validation;

import inf5153emf.Commande;


/**
 * A sample validator interface for {@link inf5153emf.Memento}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MementoValidator {
	boolean validate();

	boolean validateCommande(Commande value);

}
