/**
 *
 * $Id$
 */
package inf5153emf.validation;

import inf5153emf.Observeur;
import inf5153emf.TableVerite;

/**
 * A sample validator interface for {@link inf5153emf.Subject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubjectValidator {
	boolean validate();

	boolean validateNotify(Observeur value);

	boolean validateUse(TableVerite value);

	boolean validateTableverite(TableVerite value);

	boolean validateNotifies(Observeur value);
}
