/**
 *
 * $Id$
 */
package inf5153emf.validation;

import inf5153emf.CircuitLogic;
import inf5153emf.Porte;


/**
 * A sample validator interface for {@link inf5153emf.TableVerite}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableVeriteValidator {
	boolean validate();

	boolean validatePorte(Porte value);
	boolean validateCircuitlogic(CircuitLogic value);
	boolean validateEntree(int value);
	boolean validateSortie(int value);

}
